directories:
  BINARIES: ../agamemnon/binaries
  CONFIG_DIR: .
  CONTROL_INDEX: ../agamemnon/dump_test/hisat2_control_index/phix/phix
  HOST_INDEX: ../agamemnon/dump_test/hisat2_control_index/phix/phix
  INDEX_FASTQ: NA
  PUFFERFISH_INDEX: ../agamemnon/dump_test/puff_index
  RESULTS: ../agamemnon/results
  SAMPLES_DIR: ../agamemnon/dump_test/dataset
  SCRIPTS: ../agamemnon/scripts
  TAXONOMY_FILE: ../agamemnon/Taxonomy/
parameters:
  ALGORITHM: agamemnon
  CLEAR_ALL: 'False'
  FILES_EXT: .fq
  HOST_SAM: 'False'
  MODE: '1'
  STRATEGY: PE
  TYPE: DNA
resources:
  MEM_MB: 1
  TPS: 4
