directories:
  BINARIES: "../agamemnon-master/binaries"
  CONFIG_DIR: .
  CONTROL_INDEX: NA
  HOST_INDEX: NA
  INDEX_FASTQ: NA
  PUFFERFISH_INDEX: ""
  RESULTS: ""
  SAMPLES_DIR: ""
  SCRIPTS: "../agamemnon-master/scripts"
  TAXONOMY_FILE: "../agamemnon-master/Taxonomy"
parameters:
  ALGORITHM: agamemnon
  CLEAR_ALL: 'False'
  FILES_EXT: ".fq"
  HOST_SAM: 'False'
  MODE: '1'
  STRATEGY: PE
  TYPE: RNA
resources:
  MEM_MB: 1
  TPS: 8
